-- Info Tarkov: admin surface hardening.
-- Run once in the Supabase SQL editor after reviewing the current db_pre_request setting.
-- This migration intentionally does not change user-facing application data.

begin;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null,
  request_path text not null,
  request_method text not null,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;
revoke all on table public.admin_audit_log from public, anon, authenticated;
revoke all on sequence public.admin_audit_log_id_seq from public, anon, authenticated;

create or replace function public.assert_admin_aal2()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'Not authenticated' using errcode = '42501';
  end if;

  if coalesce((select auth.jwt()->>'aal'), 'aal1') <> 'aal2' then
    raise exception 'MFA verification required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.user_roles
    where public.user_roles.user_id = (select auth.uid())
      and public.user_roles.role = 'admin'
  ) then
    raise exception 'Not authorized' using errcode = '42501';
  end if;
end;
$$;

revoke execute on function public.assert_admin_aal2() from public, anon;
grant execute on function public.assert_admin_aal2() to authenticated;

create or replace function public.list_admin_users_secure(
  search_text text default '',
  role_filter text default 'all',
  activity_filter text default 'all',
  page_limit integer default 50,
  page_offset integer default 0
)
returns table (
  user_id uuid,
  masked_email text,
  username text,
  tarkov_username text,
  auth_username text,
  auth_tarkov_username text,
  role text,
  created_at timestamptz,
  last_seen timestamptz,
  is_owner boolean,
  total_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.assert_admin_aal2();

  return query
  with users_with_activity as (
    select
      users.id,
      users.email::text as full_email,
      coalesce(profiles.username, profiles.tarkov_username, users.raw_user_meta_data->>'username', users.raw_user_meta_data->>'tarkov_username')::text as display_username,
      profiles.tarkov_username::text as profile_tarkov_username,
      (users.raw_user_meta_data->>'username')::text as metadata_username,
      (users.raw_user_meta_data->>'tarkov_username')::text as metadata_tarkov_username,
      coalesce(roles.role, 'user')::text as effective_role,
      users.created_at as registered_at,
      max(sessions.last_seen) as latest_seen
    from auth.users as users
    left join public.user_profiles as profiles on profiles.user_id = users.id
    left join public.user_roles as roles on roles.user_id = users.id
    left join public.app_active_sessions as sessions on sessions.user_id = users.id
    group by users.id, users.email, users.raw_user_meta_data, users.created_at,
      profiles.username, profiles.tarkov_username, roles.role
  ), filtered as (
    select *
    from users_with_activity
    where (
      coalesce(trim(search_text), '') = ''
      or lower(coalesce(display_username, '')) like '%' || lower(trim(search_text)) || '%'
      or lower(coalesce(full_email, '')) like '%' || lower(trim(search_text)) || '%'
    )
      and (role_filter = 'all' or effective_role = role_filter)
      and (
        activity_filter = 'all'
        or (activity_filter = 'online' and latest_seen >= now() - interval '2 minutes')
        or (activity_filter = 'offline' and (latest_seen is null or latest_seen < now() - interval '2 minutes'))
      )
  )
  select
    filtered.id,
    case
      when position('@' in filtered.full_email) > 1 then
        left(split_part(filtered.full_email, '@', 1), 2) || '***@' || split_part(filtered.full_email, '@', 2)
      else '***'
    end,
    filtered.display_username,
    filtered.profile_tarkov_username,
    filtered.metadata_username,
    filtered.metadata_tarkov_username,
    filtered.effective_role,
    filtered.registered_at,
    filtered.latest_seen,
    filtered.full_email = 'juancarfele@gmail.com',
    count(*) over ()
  from filtered
  order by filtered.registered_at desc
  limit greatest(1, least(coalesce(page_limit, 50), 100))
  offset greatest(coalesce(page_offset, 0), 0);
end;
$$;

revoke execute on function public.list_admin_users_secure(text, text, text, integer, integer) from public, anon;
grant execute on function public.list_admin_users_secure(text, text, text, integer, integer) to authenticated;

create or replace function public.admin_get_user_identity_secure(target_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  perform public.assert_admin_aal2();

  select jsonb_build_object('email', users.email::text)
  into result
  from auth.users as users
  where users.id = target_user_id;

  return coalesce(result, '{}'::jsonb);
end;
$$;

revoke execute on function public.admin_get_user_identity_secure(uuid) from public, anon;
grant execute on function public.admin_get_user_identity_secure(uuid) to authenticated;

create or replace function public.enforce_admin_api_security()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_path text := coalesce(current_setting('request.path', true), '');
  request_method text := coalesce(current_setting('request.method', true), 'UNKNOWN');
  protected_rpc boolean :=
    request_path like '/rpc/admin\_%' escape '\'
    or request_path in (
      '/rpc/list_admin_users',
      '/rpc/list_admin_users_secure',
      '/rpc/list_admin_feedback',
      '/rpc/get_admin_app_stats'
    );
begin
  if not protected_rpc then
    return;
  end if;

  perform public.assert_admin_aal2();

  insert into public.admin_audit_log (admin_user_id, request_path, request_method)
  values ((select auth.uid()), request_path, request_method);
end;
$$;

revoke execute on function public.enforce_admin_api_security() from public;
grant execute on function public.enforce_admin_api_security() to anon, authenticated;

-- Supabase/PostgREST functions are executable by PUBLIC unless explicitly revoked.
-- Keep the browser-facing RPCs available only to authenticated sessions; the
-- pre-request hook above then requires both the admin role and an AAL2 token.
do $$
declare
  function_signature text;
begin
  for function_signature in
    select p.oid::regprocedure::text
    from pg_proc as p
    join pg_namespace as n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = any(array[
        'list_admin_users',
        'get_admin_app_stats',
        'list_admin_feedback',
        'admin_get_user_progress',
        'admin_set_user_role',
        'admin_delete_user',
        'admin_send_user_message',
        'admin_update_feedback_status',
        'admin_reply_feedback',
        'admin_delete_feedback'
      ])
  loop
    execute format('revoke execute on function %s from public, anon', function_signature);
    execute format('grant execute on function %s to authenticated', function_signature);
  end loop;
end;
$$;

-- Fail closed instead of silently replacing another project-wide pre-request hook.
do $$
declare
  existing_hook text;
begin
  select setting
  into existing_hook
  from (
    select split_part(config, '=', 2) as setting
    from pg_roles,
      lateral unnest(coalesce(rolconfig, array[]::text[])) as config
    where rolname = 'authenticator'
      and config like 'pgrst.db_pre_request=%'
  ) as configured_hook;

  if existing_hook is not null and existing_hook <> 'public.enforce_admin_api_security' then
    raise exception 'Existing pgrst.db_pre_request hook found: %. Merge it before applying this migration.', existing_hook;
  end if;
end;
$$;

alter role authenticator
  set pgrst.db_pre_request = 'public.enforce_admin_api_security';

notify pgrst, 'reload config';

commit;
