[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/pmc-profile"
  to = "/.netlify/functions/pmc-profile"
  status = 200

[[redirects]]
  from = "/api/image-proxy"
  to = "/.netlify/functions/image-proxy"
  status = 200

[[redirects]]
  from = "/api/goons-tracker"
  to = "/.netlify/functions/goons-tracker"
  status = 200
