export const FALLBACK_BOSSES = [
  {
    id: 'bigpipe',
    name: 'BIG PIPE',
    fileName: 'bigpipe.jpg',
    mapaDefault: 'Customs, Lighthouse, Shoreline, Woods',
    spawnDefault: '30%',
    dificultad: 'Medium',
    colorDificultad: '#ffcc00',
    guardias: 'Accompanied by Knight and Birdeye (The Goons)',
    fisico: 'Massive build, extensive tattoos and his signature mechanical pipe.',
    actitud: 'Extremely aggressive. Pushes and flanks at close range while Knight applies pressure.',
    armas: 'MGL 40mm, Remington 870, Colt M4A1',
    municion: '40x46mm HE, 12/70 AP-20, 5.56x45mm M855A1',
    debiles: 'Unprotected head, no heavy helmet, and exposed joints.',
    loot: 'MGL grenade launcher, Pipe special backpack and high-priority keys.'
  },
  {
    id: 'birdeye',
    name: 'BIRDEYE',
    fileName: 'birdeye.jpg',
    mapaDefault: 'Customs, Lighthouse, Shoreline, Woods',
    spawnDefault: '30%',
    dificultad: 'Medium',
    colorDificultad: '#ffcc00',
    guardias: 'Accompanied by Knight and Big Pipe (The Goons)',
    fisico: 'Light camouflage equipment and advanced tactical headset.',
    actitud: 'Silent marksman. Repositions constantly and his footsteps are barely audible.',
    armas: 'Remington M700, SR-25, M4A1',
    municion: '7.62x51mm M61 / M993, 5.56x45mm SSA AP',
    debiles: 'Exposed torso and limbs; lacks sustained heavy armor.',
    loot: 'Modified bolt-action rifle, access cards and premium military ammunition.'
  },
  {
    id: 'glukhar',
    name: 'GLUKHAR',
    fileName: 'glukhar.jpg',
    mapaDefault: 'Reserve',
    spawnDefault: '75%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: '6 to 7 heavily armored guards',
    fisico: 'Russian urban camouflage uniform, robust build and no helmet.',
    actitud: 'Strategic and defensive. His guards split into assault, scout and marksman roles.',
    armas: 'AS VAL, M1A, ASH-12',
    municion: '9x39mm SP-6 / BP, 7.62x51mm M62, 12.7x55mm PS12B',
    debiles: 'Head shots, especially if isolated from his assault guards.',
    loot: 'Reserve military keys, FIR ASH-12 and high-capacity magazines.'
  },
  {
    id: 'kaban',
    name: 'KABAN',
    fileName: 'kaban.jpg',
    mapaDefault: 'Streets of Tarkov',
    spawnDefault: '75%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: 'Large group of armored guards and static snipers',
    fisico: 'Huge frame, heavy civilian clothing and entrenched position in the car dealership.',
    actitud: 'Static but lethal. Uses mounted heavy machine guns and relentless sustained fire.',
    armas: 'PKP Pecheneg, PKM, Tokarev TT-33',
    municion: '7.62x54mmR SNB / BT, 7.62x25mm PST',
    debiles: 'Extremely limited mobility; vulnerable to flanks and grenades.',
    loot: 'PKP/PKM machine gun, Streets keys and full ammunition cases.'
  },
  {
    id: 'killa',
    name: 'KILLA',
    fileName: 'killa.jpg',
    mapaDefault: 'Interchange',
    spawnDefault: '75%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: 'Spawns completely alone',
    fisico: 'Black tracksuit with three stripes, 6B13 armor and Maska helmet with visor.',
    actitud: 'Relentless hunter. Runs toward footstep audio and fires long bursts.',
    armas: 'RPK-16, PP-19-01 Vityaz, AK-74M',
    municion: '5.45x39mm 7N40 / Igolnik, 9x19mm PBP',
    debiles: 'Side blind spots, back of the head and legs.',
    loot: 'Maska-1Sch helmet and level 5 Killa polyethylene body armor.'
  },
  {
    id: 'knight',
    name: 'KNIGHT',
    fileName: 'knight.jpg',
    mapaDefault: 'Customs, Lighthouse, Shoreline, Woods',
    spawnDefault: '30%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: 'Leader of the trio, accompanied by Big Pipe and Birdeye',
    fisico: 'Ballistic skull mask and modular assault plate carrier.',
    actitud: 'Spearhead operator. Detects targets at extreme range and starts lethal pursuits.',
    armas: 'FN SCAR-H, MDR 5.56, Glock 18C',
    municion: '7.62x51mm BCP FMJ / M80, 5.56x45mm M855A1',
    debiles: 'Ballistic mask visor and lower limbs.',
    loot: 'Skull mask, assault plate carrier and advanced stimulants.'
  },
  {
    id: 'kollontay',
    name: 'KOLLONTAY',
    fileName: 'kollontay.jpg',
    mapaDefault: 'Streets of Tarkov',
    spawnDefault: '75%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: '3 to 5 guards with Russian police equipment',
    fisico: 'Former military police uniform, officer cap and riot baton.',
    actitud: 'Psychological pressure. If he gets too close, he uses the baton and can force weapon blocking.',
    armas: 'RPK-16, Stechkin APS, rubber baton',
    municion: '5.45x39mm PPBS / BP, 9x18mm PM PBM',
    debiles: 'Side torso angles; vulnerable while sprinting in with the baton.',
    loot: 'Unique Kollontay baton, Streets police station keys and police equipment.'
  },
  {
    id: 'partisan',
    name: 'PARTISAN',
    fileName: 'partisan.jpg',
    mapaDefault: 'Customs, Woods, Shoreline, Factory',
    spawnDefault: '25%',
    dificultad: 'Medium',
    colorDificultad: '#ffcc00',
    guardias: 'Spawns completely alone',
    fisico: 'Worn woodland camouflage, thick beard and large tactical backpack.',
    actitud: 'Hostile trapper. Places tripwire grenades and stalks from vegetation.',
    armas: 'Modified AKM, SKS, tripwire traps',
    municion: '7.62x39mm BP / PP, F-1 / VOG-25 grenades',
    debiles: 'Easy to drop in open terrain if his traps are detected before contact.',
    loot: 'Tripwire kit, collector AKM and smuggler dogtags.'
  },
  {
    id: 'reshala',
    name: 'RESHALA',
    fileName: 'reshala.jpg',
    mapaDefault: 'Customs',
    spawnDefault: '75%',
    dificultad: 'Medium',
    colorDificultad: '#ffcc00',
    guardias: '4 elite Zavodskoy guards',
    fisico: 'Brown leather jacket with gold patterns and no visible armor.',
    actitud: 'Cowardly and evasive. Hides while his guards assault and secure the area.',
    armas: 'Golden TT pistol, AK-101, AK-74N',
    municion: 'PST Gzh, 5.56x45mm M856A1, 5.45x39mm BT',
    debiles: 'Torso and head; he has no native body armor.',
    loot: 'Collector golden TT pistol, Customs office key and bitcoins.'
  },
  {
    id: 'sanitar',
    name: 'SANITAR',
    fileName: 'sanitar.jpg',
    mapaDefault: 'Shoreline',
    spawnDefault: '75%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: '2 heavily armed guards',
    fisico: 'Blue medical coat over civilian clothing and a surgical kit bag.',
    actitud: 'Dynamic support. Constantly heals and buffs his guards during combat.',
    armas: 'VSS Vintorez, OP-SKS, Kedr-B',
    municion: '9x39mm SP-5, 7.62x39mm PS, 9x18mm SP7',
    debiles: 'Unprotected head and animation windows while injecting stimulants.',
    loot: 'Medical case with rare stimulants, Ophthalmoscope, LedX and syringes.'
  },
  {
    id: 'shturman',
    name: 'SHTURMAN',
    fileName: 'shturman.jpg',
    mapaDefault: 'Woods',
    spawnDefault: '75%',
    dificultad: 'Hard',
    colorDificultad: '#ffaa00',
    guardias: '2 guards equipped with long-range rifles',
    fisico: 'Winter coat with fur hood, exposed face and strong sawmill control.',
    actitud: 'Zone sniper. Shoots at extreme distances with calculated cadence.',
    armas: 'SVDS, AK-105',
    municion: '7.62x54mmR 7N1 / SNB, 5.45x39mm BT',
    debiles: 'Head and limbs without rigid ballistic armor.',
    loot: "Shturman's stash key, modified SVDS and red access cards."
  },
  {
    id: 'tagilla',
    name: 'TAGILLA',
    fileName: 'tagilla.jpg',
    mapaDefault: 'Factory',
    spawnDefault: '75%',
    dificultad: 'Medium',
    colorDificultad: '#ffcc00',
    guardias: 'Spawns completely alone',
    fisico: 'Low welding trousers, tattooed torso and heavy welding mask.',
    actitud: 'Relentless close-range assault. Chases with the sledgehammer and forces close combat.',
    armas: "Tagilla's hammer, Saiga-12, MP-155 Ultima",
    municion: '12/70 Flechette / AP-20, Magnum buckshot',
    debiles: 'Exposed back and legs with high flesh-damage vulnerability.',
    loot: "Level 5 welding mask, Tagilla's rigid plate carrier and sledgehammer."
  },
  {
    id: 'Zryachiy',
    name: 'Zryachiy',
    fileName: 'zryachiy.jpg',
    mapaDefault: 'Lighthouse',
    spawnDefault: '100%',
    dificultad: 'Very Hard',
    colorDificultad: '#ff4444',
    guardias: '2 support snipers hidden on the island slopes',
    fisico: 'White balaclava with stitched pattern and optic mounted at the eye.',
    actitud: 'Absolute defensive sniper. Opens fire if you cross the bridge without an active transmitter.',
    armas: 'AXMC .338, SV-98',
    municion: '.338 Lapua Magnum AP, 7.62x54mmR BS',
    debiles: 'Static defensive position; vulnerable if you break his initial line of sight.',
    loot: 'AXMC .338 tactical rifle, collector Lapua AP ammunition and military telemetry.'
  },
  {
    id: 'wedge',
    name: 'WEDGE',
    fileName: 'wedge.jpg',
    mapaDefault: 'Icebreaker',
    spawnDefault: 'TBD',
    dificultad: 'Very Hard',
    colorDificultad: '#ff4444',
    guardias: 'Black Division boss with 3 to 6 followers depending on the number of players in the raid',
    fisico: 'Black EXFIL helmet with visor, Avon gas mask and Spiritus LV-119 plate carrier.',
    actitud: 'Elite Black Division contact on Icebreaker level 3. Treat as a coordinated squad with heavy armor and high-penetration ammunition.',
    armas: 'HK MP7A1, FN SCAR-H, X-17, DS Arms SA-58, Desert Tech MDR, HK USP and SOG Voodoo Hawk',
    municion: '4.6x30mm AP SX, 5.56x45mm M995, 7.62x51mm M993, .45 ACP AP',
    debiles: 'High health pool and 3-6 followers; isolate guards first and avoid exposed angles on Icebreaker.',
    loot: 'Spiritus LV-119 plate carrier, keycard holder case, Euros, Dollars and Black Division gear.'
  }
];
